<div style="padding:20px 0px 20px 0px; text-align:center; font-weight: bold; font-size:150%; background-color: #cce6ff"> 08.1. Data Science - NumPy
</div>

# Διανύσματα

## Τοπικά μέγιστα

Με δεδομένο έναν πίνακα NumPy, έστω _a_, ακεραίων αριθμών βρείτε και αποθηκεύστε σε έναν πίνακα, έστω _b_ τους δείκτες των κορυφών. Κορυφές θεωρούνται τα στοιχεία που αριστερά και δεξιά τους έχουν μικρότερες τιμές.

Παράδειγμα κλήσης:
```
>>>a = np.array([4, 6, 3, 8, 9, 7, 4, 2, 6, 5])

...

array([1, 4, 8], dtype=int64)
```

Επεξήγηση:

- Το στοιχείο 1 που είναι 6 είναι μεγαλύτερο από τα στοιχεία 0 (4) και 2 (3).

- Το στοιχείο 4 (9) είναι μεγαλύτερο από τα 3 (8) και 5 (7).

- Το στοιχείο 8 (6) είναι μεγαλύτερο από τα 7 (2) και 9 (5).

In [ ]:
import numpy as np
a = np.array([4, 6, 3, 8, 9, 7, 4, 2, 6, 5])

## n-στη εμφάνιση

Υλοποιήστε συνάρτηση, έστω _getRepetition_, η οποία δέχεται έναν πίνακα NumPy, _a_, αριθμό, _num_, και φυσικό αριθμό, _n_, και επιστρέφει τη θέση της n-στης εμφάνισης του αριθμού _num_ στον πίνακα _a_. Σε περίπτωση που ο αριθμός _num_ δεν εμφανίζεται _n_ φορές θα επιστρέφεται -1.

Παράδειγμα κλήσης:
```
>>>a = np.array([1, 5, 4, 1, 2, 1, 2, 9, 4, 2, 3, 1, 1, 2, 1, 3, 4])
>>>getRepetition(a,1,4)

7

>>>getRepetition(a,1,8)

-1
```

In [ ]:
a = np.array([1, 5, 4, 1, 2, 1, 2, 9, 4, 2, 3, 1, 1, 2, 1, 3, 4])
n = 4
num = 1

## Κινούμενος μέσος όρος

Να υλοποιηθεί συνάρτηση, έστω _movingAverage_, η οποία δέχεται διάνυσμα NumPy, _a_, και αριθμό, _w_, και επιστρέφει πίνακα με τον κινητό μέσο όρο του πίνακα _a_ με παράθυρο _w_.

Ο κινητός μέσος όρος για κάθε στοιχείο, εκτός των πρώτων και τελευταίων στοιχείων που δεν έχουν τα απαιτούμενα γειτονικά στοιχεία, θα υπολογίζεται ως ο μέσος όρος των w διαδοχικών αριθμών Ο w θα πρέπει να είναι περιττός και θετικός, όχι μεγαλύτερος από τον αριθμό στοιχείων του αρχικού πίνακα. Στο επόμενο παράδειγμα, ο τύπος δίνει το κάθε στοιχείο για w=3.
$$
MA(i) = \frac{a[i-1] + a[i] + a[i+1]}{3}
$$

Οι ακραίες τιμές του πίνακα, για τις οποίες δεν μπορεί να προκύψει μέσος όρος θα πρέπει να οριστούν ως `np.NaN`

Για τον πίνακα:
$$
a = [1,\ 5,\ 3,\ 6,\ 8,\ 2,\ 7]
$$
Ο πίνακας που θα προκύψει από την διαδικασία
$$
MA = [\text{NaN},\ 3.0,\ 4.67,\ 5.67,\ 5.33,\ 5.67,\ \text{NaN}]
$$
Παράδειγμα κλήσης:
```
>>>a = np.array([1, 5, 3, 6, 8, 2, 7])
>>>movingAverage(a, 3)

array([ nan, 3.  , 4.67, 5.67, 5.33, 5.67,  nan])
```

In [ ]:
a = [1, 5, 3, 6, 8, 2, 7]
w = 3

## Αποστάσεις

Να υλοποιηθούν συναρτήσεις python οι οποίες δέχονται σημεία ως tuples συντεταγμένων τα μετατρέπουν σε πίνακες NumPy και υπολογίζουν και επιστρέφουν τις επόμενες αποστάσεις.

1. Συνάρτηση _euclideanDistance_ για την ευκλείδεια απόσταση.
$$
d_{\text{Euclidean}}(A, B) = \sqrt{\sum_{i=1}^{n} (A_i - B_i)^2}
$$

2. Συνάρτηση _manhattanDistance_ για την απόσταση Μανχάταν.
$$
d_{\text{Manhattan}}(A, B) = \sum_{i=1}^{n} |A_i - B_i|
$$

3. Συνάρτηση _minkowskiDistance_ για την απόσταση Minkowski που αποτελεί και γενίκευση των παραπάνω αποστάσεων. Η συνάρτηση αυτή, πέρα από τα σημεία θα δέχεται και την παράμετρο p. Θα πρέπει για p=1 να επιστρέφει ίδια αποτελέσματα με την _manhattanDistance_ και για p=2 ίδια με την _euclideanDistance_. Η συνάρτηση θα πρέπει να έχει εξορισμού τιμή p=3.
$$
d_{\text{Minkowski}, p}(A, B) = \left( \sum_{i=1}^{n} |A_i - B_i|^p \right)^{\frac{1}{p}}
$$

Στην συνέχεια απεικονίζονται οι αποστάσεις για τις παραπάνω περιπτώσεις
$$
\begin{array}{c c c}
\textbf{Ευκλείδεια} & \textbf{Manhattan} & \textbf{Minkowski (p=3)} \\ 
\hline
\begin{bmatrix} 
\sqrt{2} & 1 & \sqrt{2} \\ 
1 & 0 & 1 \\ 
\sqrt{2} & 1 & \sqrt{2} 
\end{bmatrix} 
&
\begin{bmatrix} 
2 & 1 & 2 \\ 
1 & 0 & 1 \\ 
2 & 1 & 2 
\end{bmatrix} 
&
\begin{bmatrix} 
1.26 & 1 & 1.26 \\ 
1 & 0 & 1 \\ 
1.26 & 1 & 1.26 
\end{bmatrix} 
\end{array}
$$

Παράδειγμα κλήσης:
```
>>>A = (1, 2)
>>>B = (4, 6)
>>>euclideanDistance(A,B)

5.0
>>>manhattanDistance(A,B)

7
>>>minkowskiDistance(A,B)

4.497941445275415
```

4. Ο αλγόριθμος K-Nearest Neighbors αποτελεί έναν δημοφιλή αλγόριθμο μηχανικής μάθησης για ταξινόμηση δεδομένων σε κατηγορίες, βασισμένος στην αρχή ότι τα παρόμοια δεδομένα τείνουν να είναι κοντά το ένα στο άλλο στο χώρο των χαρακτηριστικών. Ο αριθμός _k_ αναφέρεται στον αριθμό των κοντινότερων γειτόνων που λαμβάνονται υπόψη για να ληφθεί η απόφαση ταξινόμησης. Υλοποιήστε συνάρτηση _kNearestNeighbors_ η οποία δέχεται:

- μία λίστα σημείων, δηλαδή λίστα από tuples.

- ένα σημείο αναφοράς, ως tuple με την ίδια διάσταση με τα tuples της παραπάνω λίστας σημείων.

- το k του k-nearest neighbors. 

- την συνάρτηση υπολογισμού απόστασης, παράδειγμα euclideanDistance ή minkowskiDistance.

Η συνάρτηση επιστρέφει τα k, πλησιέστερα στο σημείο αναφοράς, σημεία.

Παράδειγμα κλήσης:
```
>>>points = [(1, 2), (3, 4), (5, 6), (7, 8)]
>>>refpoint = [4, 4]
>>>kNearestNeighbors(points, refpoint, 2,euclideanDistance)

[(3, 4), (5, 6)]
```

In [ ]:
A = (1, 2)
B = (4, 6)

In [ ]:
points = [(1, 2), (3, 4), (5, 6), (7, 8)]

# Πίνακες

## Αντιμεταθέσεις γραμμών, στηλών

1. Δημιουργήστε τον επόμενο 3x3 πίνακα NumPy.
$$
\begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5 \\
6 & 7 & 8 \\
\end{bmatrix}
$$

2. Αντιμεταθέστε τις στήλες 1 και 2 ώστε να προκύψει ο επόμενος πίνακας:
$$
\begin{bmatrix}
0 & 2 & 1 \\
3 & 5 & 4 \\
6 & 8 & 7 \\
\end{bmatrix}
$$

3. Αντιμεταθέστε τις γραμμές 0 και 2 ώστε να προκύψει ο επόμενος πίνακας:
$$
\begin{bmatrix}
6 & 8 & 7 \\
3 & 5 & 4 \\
0 & 2 & 1 \\
\end{bmatrix}
$$

## Πωλήσεις

Δίνεται ο πίνακας _sales_ ο οποίος απεικονίζει τις πωλήσεις, σε χιλιάδες €, για τρεις γεύσεις παγωτού, Βανίλια, Σοκολάτα και Ντουμπάι, για 12 μήνες του έτους. Υπολογίστε και εμφανίστε:

1. Μέσο όρο πωλήσεων ανά μήνα για κάθε γεύση καθώς και συνολικές πωλήσεις για κάθε γεύση παγωτού για το έτος.

Παράδειγμα:
```
Μέσος όρος πωλήσεων ανά μήνα:
Ιανουάριος : 17.67 χιλ. €
Φεβρουάριος : 20.0 χιλ. €

Συνολικές πωλήσεις για κάθε γεύση:
Βανίλια : 321 χιλ. €
Σοκολάτα : 357 χιλ. €
Ντουμπάι : 401 χιλ. €
```

2. Μέσες πωλήσεις ανά τρίμηνο καθώς και μέσες πωλήσεις για τους καλοκαιρινούς μήνες (Ιούνιος, Ιούλιος, Αύγουστος). Επιπλέον, βρείτε τη γεύση με τις υψηλότερες πωλήσεις το καλοκαίρι.

Παράδειγμα:
```
Μέσες πωλήσεις ανά τρίμηνο:
Τρίμηνο 1 : [17.         20.         22.66666667]
Τρίμηνο 2 : [27.33333333 30.         33.33333333]
Τρίμηνο 3 : [41.         45.66666667 50.66666667]
Τρίμηνο 4 : [21.66666667 23.33333333 27.        ]

Μέσες πωλήσεις για το καλοκαίρι (Ιούνιος, Ιούλιος, Αύγουστος):
Βανίλια : 40.0 χιλ. €
Σοκολάτα : 44.33 χιλ. €
Ντουμπάι : 49.0 χιλ. €

Γεύση με τις υψηλότερες πωλήσεις το καλοκαίρι: Ντουμπάι
```


3. Μήνας με υψηλότερες πωλήσεις συνολικά και ποια γεύση είχε τις υψηλότερες πωλήσεις στους μήνες αυτούς.
```
Μήνας με υψηλότερες συνολικές πωλήσεις:
Αύγουστος : 150 χιλ. €
Γεύση με τις υψηλότερες πωλήσεις το μήνα Αύγουστος : Ντουμπάι
```

In [ ]:
months = [
    'Ιανουάριος', 'Φεβρουάριος', 'Μάρτιος', 'Απρίλιος', 'Μάιος', 'Ιούνιος', 
    'Ιούλιος', 'Αύγουστος', 'Σεπτέμβριος', 'Οκτώβριος', 'Νοέμβριος', 'Δεκέμβριος'
]
flavors = ['Βανίλια', 'Σοκολάτα', 'Ντουμπάι']
sales = np.array([
    [15, 18, 20],  # Ιανουάριος
    [17, 20, 23],  # Φεβρουάριος
    [19, 22, 25],  # Μάρτιος
    [22, 24, 28],  # Απρίλιος
    [25, 28, 30],  # Μάιος
    [35, 38, 42],  # Ιούνιος
    [40, 45, 50],  # Ιούλιος
    [45, 50, 55],  # Αύγουστος
    [38, 42, 47],  # Σεπτέμβριος
    [28, 30, 35],  # Οκτώβριος
    [20, 22, 25],  # Νοέμβριος
    [17, 18, 21]   # Δεκέμβριος
])

## Μαγικό τετράγωνο

Το μαγικό τετράγωνο αποτελεί μια διάταξη μοναδικών αριθμών σε τετραγωνικό πίνακα, όπου η αριθμητική πράξη μεταξύ των αριθμών στην ίδια σειρά, στήλη και διαγώνιο του τετραγώνου επιστρέφει πάντα το ίδιο αποτέλεσμα. Αν η πράξη είναι η πρόσθεση, το αποτέλεσμα για ένα μαγικό τετράγωνο $n \times n$ δίνεται από τον τύπο $M = \frac{n(n^2 + 1)}{2}$. Επιπλέον οι αριθμοί που θα περιέχει το τετράγωνο θα είναι από 1 έως $n^2$.

Ένα μαγικό τετράγωνο 3×3 με M = 15:

$$
\begin{array}{|c|c|c|}
\hline
8 & 1 & 6 \\
\hline
3 & 5 & 7 \\
\hline
4 & 9 & 2 \\
\hline
\end{array}
$$

1. Υλοποιήστε συνάρτηση, έστω readSquare(filename), η οποία δέχεται αρχείο με αριθμούς χωρισμένους με ',' όπως στην συνέχεια και επιστρέφει πίνακα NumPy.
```
8,1,6  
3,5,7  
4,9,2
```

Παράδειγμα κλήσης:
```
>>>readSquare("magic_true.txt")

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])
```

2. Υλοποιήστε συνάρτηση, έστω isMagic(square), που δέχεται έναν πίνακα NumPy και επιστρέφει True αν αποτελεί μαγικό τετράγωνο. Διαφορετικά επιστρέφει False.

Παράδειγμα κλήσης:
```
>>>a = readSquare("magic_true.txt")
>>>isMagic(a)

True

>>>b = readSquare("magic_false.txt")
>>>isMagic(b)

False
```