<div style="padding:20px 0px 20px 0px; text-align:center; font-weight: bold; font-size:150%; background-color: #cce6ff"> 08.1. Data Science - NumPy
</div>

Η NumPy, Numerical Python, χρησιμοποιείται για επιστημονικούς υπολογισμούς και επεξεργασία δεδομένων. Βρίσκει εφαρμογή σε ανάλυση δεδομένων, μηχανική μάθηση και επιστημονικούς υπολογισμούς.

<a id="numpy_import"></a>
# Εισαγωγή βιβλιοθήκης

Παραδοσιακά το πακέτο NumPy εισάγεται με το alias `np`. Αυτό μπορεί να επιτευχθεί με την επόμενη δήλωση.

In [2]:
import numpy as np

# Διανύσματα

## Δημιουργία

### Λίστα

Ο βασικός τύπος που παρέχεται από την NumPy είναι ο `ndarray`. Η μέθοδος `array` δημιουργεί έναν τέτοιο πίνακα από οποιοδήποτε αντικείμενο πίνακα, συνηθέστερα μία λίστα. Σε αντίθεση, όμως, με την λίστα, ο `ndarray` πρέπει να αποτελείται από ιδίου τύπου στοιχεία.

In [ ]:
arr1 = np.array([1.,2.,3.]);arr1

Στην συνέχεια η λίστα δημιουργείται με **comprehension**.

In [ ]:
arr2 = np.array([n**2 for n in range(10)]);arr2

### Μηδέν ή ένα

Οι μέθοδοι `np.zeros`, `np.ones` δημιουργούν πίνακες με όλα τα στοιχεία 0 και 1 αντίστοιχα.

In [ ]:
np.zeros(5),np.ones(8)

### Τυχαία στοιχεία

Η NumPy παρέχει μία σειρά από μεθόδους δημιουργίας πινάκων με τυχαία στοιχεία.

 Η `np.random.rand(n)` δημιουργεί λίστα _n_ ακεραίων στο [0,1) που ακολουθούν την ομοιόμορφη κατανομή.

In [ ]:
np.random.rand(5)

Ομοιόμορφα κατανεμημένα αριθμούς παίρνουμε και με την `np.random.uniform(low, high, size)`. Καλώντας την θα πάρουμε _size_ πραγματικούς στο διάστημα [_low_,_high_).

In [ ]:
np.random.uniform(low=0, high=10, size=10)

**Παράδειγμα**

Θα δημιουργήσουμε 1.000.000 πραγματικούς στο διάστημα [0,100) και θα δούμε ποιο ποσοστό αριθμών βρίσκεται στο διάστημα (10,20]. Το ποσοστό αυτό, εφόσον οι τυχαίοι ακολουθούν ομοιόμορφη κατανομή θα είναι κοντά στο 0.1. 

Σημείωση: Η `sum` θα μετατρέψει όλες τις τιμές `True` της συνθήκης (data > 10) & (data <= 20) σε 1 και θα τις αθροίσει μετρώντας ουσιαστικά τους αριθμούς στο (0,20].

In [3]:
data = np.random.uniform(low=0, high=100, size=1_000_000)
np.sum((data > 10) & (data <= 20)) / len(data)

0.099816

Η `np.random.randint(low,high,size)` δημιουργεί διάνυσμα με _size_ τυχαίους, ομοιόμορφα κατανεμημένους, ακέραιους αριθμούς στο [_low_, _high_).

In [ ]:
np.random.randint(1,10,5)

**Παράδειγμα**

Θα προσομοιώσουμε 1.000 ρίψεις ενός ζαριού με τη βοήθεια της `randint` και θα εμφανίσουμε το πλήθος κάθε ζαριάς. Θα χρησιμοποιηθεί και η `np.bincount` η οποία υπολογίζει το πλήθος εμφανίσεων κάθε τιμής και επιστρέφει αντίστοιχο πίνακα.

In [4]:
rolls = np.random.randint(1, 7, size=1000)
counts = np.bincount(rolls)
for i in range(1,7):
    print('Ζαριά ', i,': ', counts[i],' φορές')

Ζαριά  1 :  180  φορές
Ζαριά  2 :  156  φορές
Ζαριά  3 :  151  φορές
Ζαριά  4 :  178  φορές
Ζαριά  5 :  168  φορές
Ζαριά  6 :  167  φορές


Η `np.random.randn` δημιουργεί διάνυσμα με τυχαίους πραγματικούς οι οποίοι ακολουθούν κανονική κατανομή:
```
randn(πλήθος, μέση_τιμή, τυπική_απόκλιση)
```

**Παραδείγματα**

- Δημιουργία διανύσματος 4 τυχαίων ακέραιων, κανονική κατανομή με μέση τιμή 0 και τυπική απόκλιση 1.

- Δημιουργία διανύσματος 10 τυχαίων ακέραιων, κανονική κατανομή με μέση τιμή 5 και τυπική απόκλιση 2.

Η `numpy.random.normal(loc,scale,size)` δημιουργεί τυχαίους αριθμούς που ακολουθούν την κανονική κατανομή με μέση τιμή _loc_ και τυπική απόκλιση _scale_. Το _size_ καθορίζει το σχήμα του πίνακα. Αν αντί για απλός αριθμός ήταν `tuple` θα δημιουργούσε πίνακα περισσότερων διαστάσεων. H `np.random.randn(n)` δημιουργεί n τιμές που ακολουθούν την τυπική κατανομή με μέση τιμή 0 και τυπική απόκλιση 1.

In [6]:
np.random.randn(4) # np.random.normal(0, 1, 4)

array([0.64302885, 0.67452533, 0.18464199, 0.34003972])

In [7]:
np.random.normal(5, 2, 10)

array([4.67383999, 5.37587151, 6.82196928, 6.19156476, 7.42670337,
       5.80148856, 6.75809308, 5.52171105, 5.58670517, 6.94474745])

#### Σπόρος `seed`

Κάθε εκτέλεση των παραπάνω παραδειγμάτων δίνει διαφορετικά τυχαία αποτελέσματα. Σε περίπτωση που επιθυμούμε η ακολουθία (ψευδο)τυχαίων αριθμών να είναι προβλέψιμη, μπορούμε να θέσουμε έναν σπόρο, **seed**. Διαφορετικά η python θα πάρει έναν σπόρο που προκύπτει από το ρολόι του υπολογιστή και άρα, κάθε φορά που εκτελείται ο κώδικας, ο σπόρος, άρα και οι αριθμοί, θα είναι διαφορετικοί. Για να θέσουμε εμείς έναν σπόρο κάνουμε χρήση της μεθόδου `np.random.seed(n)` όπου _n_ ο σπόρος.

**Παράδειγμα**

Παράγουμε δύο λίστες 5 ψευδοτυχαίων αριθμών, με τον ίδιο όμως σπόρο. Οι αριθμοί που θα προκύψουν θα είναι πάντα οι ίδιοι.

In [ ]:
np.random.seed(42)
print(np.random.randint(1,10,5))
np.random.seed(42)
print(np.random.randint(1,10,5))

### Διαδοχικές τιμές

Μπορούμε να δημιουργήσουμε ένα διάνυσμα με τη συνάρτηση `array` και παράμετρο μια ακολουθία του τύπου `range`:

In [ ]:
np.array(range(10))

Επιπλέον, η NumPy παρέχει τις συναρτήσεις `arange` και `linspace`. 

Με χρήση της συνάρτησης `arange` της NumPy με ίδια παράμετρο με την range θα προκύψει ο ίδιος πίνακας. Η `arange`, αντίθετα με την `range`, μπορεί να δεχτεί και πραγματικούς παραμέτρους.

In [9]:
np.arange(10),np.arange(1,5,0.4)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]))

Η μέθοδος `numpy.linspace` δημιουργεί ένα διάνυσμα ισαπεχουσών τιμών με δεδομένο πλήθος σε δεδομένο διάστημα. Στο επόμενο παράδειγμα οι τιμές θα είναι 5 στο διάστημα [2,3].

In [10]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

Το δεξί άκρο του διαστήματος μπορεί προαιρετικά να εξαιρεθεί με την τιμή της προεραιτικής παραμέτρου `endpoint` να είναι False.

In [11]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

Με χρήση της παραμέτρου `retstep` μπορεί να επιστραφεί και το βήμα που θα προκύψει ανάλογα με τον αριθμό των τιμών και το διάστημα.

In [12]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

Στην `arange` οι παράμετροι είναι: 

- το διάστημα

- η απόσταση μεταξύ των τιμών

Στην `linspace`

- το διάστημα

- το πλήθος των τιμών

In [13]:
np.arange(1, 2, 0.25),np.linspace(1, 2, num=5)

(array([1.  , 1.25, 1.5 , 1.75]), array([1.  , 1.25, 1.5 , 1.75, 2.  ]))

**Παράδειγμα**

Οι επόμενες κλήσεις της `linspace` και `arange` θα επιστρέψουν τους ίδιους πίνακες.

In [ ]:
print(np.linspace(1, 2, num=4,endpoint=False))
print(np.arange(1, 2, 0.25))

## Ανακάτεμα τιμών

Οι τιμές ενός πίνακα μπορούν να ανακατευτούν in-place με την `shuffle` της `np.random`.

In [ ]:
arr = np.arange(1, 10, 1)
np.random.shuffle(arr);arr

Η `permutation` της `np.random` δημιουργεί μία τυχαία μετάθεση και την επιστρέφει ως έναν νέο πίνακα NumPy.

In [ ]:
perarr = np.random.permutation(arr);perarr

## Τύποι δεδομένων

Οι προηγούμενες κλήσεις των μεθόδων δημιουργίας πινάκων δημιούργησαν πίνακες με τους πιο κατάλληλους τύπους σε σχέση με τα δεδομένα. Η ιδιότητα `dtype` δίνει τον τύπο των δεδομένων του πίνακα και η παράμετρος με το ίδιο όνομα θέτει τον τύπο κατά την δημιουργία του πίνακα με τη μέθοδο `array`.

In [ ]:
arr1.dtype,arr2.dtype

In [ ]:
arr3 = np.array([1,2,3],dtype=np.float32);arr3

Ο τύπος των στοιχείων του πίνακα μπορεί να επανακαθοριστεί με την μέθοδο `astype`.

In [ ]:
arr4 = np.array([1,2,3])
arr4 = arr4.astype(np.float64);arr4

Ο αριθμός που ακολουθεί τον προσδιορισμό int, float είναι ο αριθμός των δυαδικών ψηφίων, bits, που καταλαμβάνει το κάθε αριθμητικό στοιχείο στην μνήμη του υπολογιστή.

Υπάρχει η δυνατότητα δημιουργίας πινάκων από `str`. Ο τύπος, τότε, του πίνακα θα είναι _Unicode_, δηλαδή U, ακολουθούμενο από το μήκος της μεγαλύτερης συμβολοσειράς του πίνακα.

In [ ]:
islands = np.array(['Samos','Ikaria','Fournoi']);islands.dtype

Το u στον επόμενο τύπο σημαίνει **unsigned** δηλαδή χωρίς πρόσημο. Με την χρήση 8 bit και την μή ύπαρξη προσήμου, μπορούν να παρασταθούν αριθμοί από 0 έως 255. Με την δοκιμή αριθμού μεγαλύτερου από 255 ή μικρότερου από 0 θα προκύψει κάποια προειδοποίηση και ο αριθμός θα τροποποιηθεί ώστε να βρίσκεται στα αποδεκτά όρια.

In [ ]:
arr5 = np.array([1,2,3,4],dtype=np.uint8);arr5

Η δήλωση ενός πραγματικού αριθμού σε πίνακα ακεραίων απλά θα προκαλέσει την μετατροπή του σε ακέραιο με αποκοπή του δεκαδικού μέρους.

In [ ]:
arr6 = np.array([1,2,3,4.8],dtype=np.int32);arr6

Η προσπάθεια, όμως, μετατροπής `str` σε ακέραιο θα προκαλέσει σφάλμα.

In [ ]:
#arr7 = np.array([1,2,3,'samos'],dtype=np.int32);arr7

## Πρόσβαση σε στοιχεία

Μπορεί κανείς να έχει πρόσβαση σε στοιχεία ενός διανύσματος `ndarray` με τον ίδιο τρόπο που μπορεί να έχει σε μία λίστα ή μία συμβολοσειρά. 

- Για να έχει πρόσβαση στο i-οστο στοιχείο, ξεκινώντας από το 0, καθορίζοντας μέσα σε αγκύλες το σχετικό δείκτη. 

- Αντίστοιχα για να ξεκινήσει από το τέλος του πίνακα μπορεί να χρσιμοποιήσει αρνητικούς δείκτες.

|   0  |   1  |   2  |   3  |
|:----:|:----:|:----:|:----:|
|  10  |  20  |  30  |  40  |
| -4   | -3   | -2   | -1   |

In [ ]:
arr = np.array([10, 20, 30, 40])
# Το πρώτο στοιχείο, Το τρίτο στοιχείο (στοιχείο με δείκτη 2), Το τελευταίο (-1) και το τρίτο από το τέλος (-3)
arr[0],arr[2],arr[-1], arr[-3]

Με τον ίδιο τρόπο με τις λίστες εκτός από μεμονωμένα στοιχεία μπορούμε να έχουμε πρόσβαση και σε περισσότερα στοιχεία κάνοντας χρήση της τεχνικής slicing, του σχήματος, δηλαδή, start:stop:step.

In [ ]:
print(arr[2:5])   # στοιχεία από τον δείκτη 2 μέχρι τον δέικτη 5 (τρίτο ως πέμπτο)
print(arr[2:])    # στοιχεία από τον δείκτη 2 και μετά (τρίτο και μετά)
print(arr[::2])   # από το 1ο έως το τελευταίο στοιχείο ανά 2
print(arr[::-1])  # από το τελευταίο έως το πρώτο στοιχείο, αντιστροφή πίνακα

Μπορούμε να πάρουμε μεμονωμένες τιμές ενός διανύσματος δίνοντας μέσα σε αγκύλες μια *λίστα* από αριθμοδείκτες, αντί ενός μεμονωμένου ακέραιου. Το παρακάτω παράδειγμα, επιστρέφει έναν υπο-πίνακα με τα στοιχεία 0, 1, 3 του αρχικού πίνακα:

In [ ]:
arr[[0, 1, 3]]

Τέλος, μπορούμε να πάρουμε τα στοιχεία ενός διανύσματος ή πίνακα με βάση κάποια συνθήκη για τα στοιχεία του πίνακα. Για παράδειγμα, μπορούμε να πάρουμε τα στοιχεία του πίνακα `arr` που διαιρούνται με το 20.

In [ ]:
arr[arr % 20 ==0]

Την ίδια λειτουργία έχουμε με την `where` μόνο που επιστρέφονται οι δείκτες των στοιχείων που ικανοποιούν την συνθήκη. Υπάρχει, βέβαια, η δυνατότητα χρησιμοποιώντας τους δείκτες να προσπελάσουμε τα ίδια τα στοιχεία.

In [ ]:
np.where(arr % 20 == 0), arr[np.where(arr % 20 == 0)]

Η λειτοργία της επανάληψης στα στοιχεία ενός πίνακα γίνεται όπως ακριβώς στα στοιχεία μίας λίστας ή άλλων δομών της Python.

In [ ]:
for a in arr:
  print (a, end= " ")
print('')

for i in range(len(arr)):
  print (arr[i], end = " ")

## Πράξεις

<a id="numpy_ops_vecs"></a>
### Διανυσμάτων

Οι αριθμητικές πράξεις `+`, `-`, `*`, `/`, `//`, `%`, `**` μεταξύ διανυσμάτων επιστρέφουν διάνυσμα με στοιχεία το άθροισμα, διαφορά, γινόμενο, πηλίκο, ακέραιο πηλίκο, ακέραιο υπόλοιπο και δύναμη των διανυσμάτων αντίστοιχα.

In [16]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a + b, a * b, a / b

(array([ 6,  8, 10, 12]),
 array([ 5, 12, 21, 32]),
 array([0.2       , 0.33333333, 0.42857143, 0.5       ]))

Οι ίδιες πράξεις μπορεί να γίνουν και με τις μεθόδους `add`, `subtract`, `multiply`, `divide`, `floor_divide`, `mod`, `power` της NumPy.

In [17]:
np.add(a,b),np.multiply(a,b),np.divide(a,b)

(array([ 6,  8, 10, 12]),
 array([ 5, 12, 21, 32]),
 array([0.2       , 0.33333333, 0.42857143, 0.5       ]))

Για να μπορούν οι παραπάνω πράξεις να μας δώσουν αποτέλεσμα θα πρέπει οι πίνακες να έχουν το ίδιο σχήμα, δηλαδή στην περίπτωση διανύσματος το ίδιο μήκος. Διαφορετικά θα προκύψει `ValueError`.

In [ ]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8,9])
# a1 + a2    # ValueError
# np.add(a1,a2) # ValueError

### Αριθμός και διάνυσμα, broadcasting

Οι πράξεις με αριθμούς και διανύσματα πραγματοποιούνται μετατρέποντας τους αριθμούς σε διανύσματα με μια διαδικασία που ονομάζεται **broadcasting**.
Έτσι για παράδειγμα, αν αφαιρέσουμε από τον πίνακα $\begin{bmatrix}5 & 10 & 15 & 20\end{bmatrix}$ τον αριθμό 5:

$$
c - 5 =
\begin{bmatrix}
5-5 & 10-5 & 15-5 & 20-5
\end{bmatrix} =
\begin{bmatrix}
0 & 5 & 10 & 15
\end{bmatrix}
$$

In [18]:
    c = np.array([5, 10, 15, 20])
    c - 5,c % 2,c ** 3

(array([ 0,  5, 10, 15]),
 array([1, 0, 1, 0], dtype=int32),
 array([ 125, 1000, 3375, 8000], dtype=int32))

<a id="numpy_math"></a>
## Μαθηματικές συναρτήσεις

Η βιβλιοθήκη numpy διαθέτει βασικές μαθηματικές συναρτήσεις, ανάλογες με τις συναρτήσεις του πακέτου math:
https://numpy.org/doc/stable/reference/routines.math.html

Κάποιες από τις συναρτήσεις που μπορούν να εφαρμοστούν: `abs`, `arcsin`, `arccos`, `arctan`, `exp`, `sqrt`, `log`, `log10`,  `sin`, `cos`, `tan`. Επιπλέον η NumPy περιέχει και χρήσιμες μαθηματικές σταθερές.

In [ ]:
import math
math.sin(math.pi/2),np.sin(np.pi/2)

Επισημαίνεται ότι μια αλγεβρική έκφραση ή μαθηματική συνάρτηση, σε δομές της python όπως η λίστα, δεν μπορεί να εφαρμοστεί απευθείας σε λίστα ή σχετική δομή. Για να επιτευχθεί κάτι τέτοιο θα πρέπει να γίνει χρήση μίας high order συνάρτησης όπως η `map`.

In [ ]:
L = [n * math.pi/8 for n in range(8)]
print(L)
list(map(math.cos, L))
# math.cos(L)   # TypeError: must be real number, not list

Διαφορετική είναι και η συμπεριφορά της πράξης του πολλαπλασιασμού ή της πρόσθεσης μίας λίστας με έναν αριθμό καθώς δεν εφαρμόζεται η τεχνική **broadcasting**.

In [ ]:
L = [1,2,3,4]
L*2 # Διπλασιασμός της λίστας
# L + 1   # TypeError: Μπορούν να συνανωθούν λίστες, όχι int με λίστα

Βασικό χαρακτηριστικό των συναρτήσεων της NumPy είναι η εφαρμογή στα στοιχεία διανυσμάτων και πινάκων

In [ ]:
L_np = np.array(L)
L_np,np.cos(L_np)

**Παράδειγμα**

Θα υπολογίσουμε την εκθετική τιμή των $e^1$, $e^2$...$e^{10}$

In [ ]:
np.exp(np.arange(1,11))

<a id="numpy_stat"></a>
## Στατιστικές συναρτήσεις 

Η NumPy διαθέτει, επιπλέον, μία σειρά στατιστικών συναρτήσεων.

Δείτε αναλυτικά: https://numpy.org/doc/stable/reference/routines.statistics.html

In [ ]:
arr = np.array([i ** 2 for i in range(0,100)]);arr

Το άθροισμα των τιμών του πίνακα μας το επιστρέφει η μεθοδος `sum`.

In [ ]:
np.sum(arr)

Η μέση τιμή των στοιχείων του μπορεί να υπολογιστεί με τις `mean` και `average`. Στην δεύτερη έχουμε την δυνατότητα να εισάγουμε και βάρη και να πάρουμε σταθμισμένο μέσο όρο.

In [ ]:
np.mean(arr),np.average(arr)

**Παράδειγμα**

θέλουμε να υπολογίσουμε το μέσο όρο της απόδοσης ενός επενδυτικού χαρτοφυλακίου, όπου κάθε επένδυση έχει διαφορετικό βάρος ποσοστό στο συνολικό κεφάλαιο. Οι αποδόσεις σε ποσοστά για τέσσερις επενδύσεις είναι: [5%, 10%, 3%, 8%]. Τα ποσοστά του συνολικού κεφαλαίου που επενδύεται σε κάθε επένδυση είναι: [0.25, 0.5, 0.15, 0.1]. Βρείτε την συνολική απόδοση του χαρτοφυλακίου.

In [ ]:
investmentyield = np.array([8,7,10,3])
weights = np.array([0.2,0.2,0.1,0.5])
np.average(investmentyield, weights=weights)

Η διάμεση τιμή, δηλαδή η μεσαία τιμή αν τα στοιχεία είναι ταξινομημένα δίνεται από την `median`.

In [ ]:
myarr = np.array([3, 1, 4, 1, 5, 9, 2]);np.median(myarr),np.sort(myarr)[len(myarr)//2]

Η ελάχιστη και μέγιστη τιμή ενός πίνακα από τις `min` και `max` αντίστοιχα με τις `argmin` και `argmax` να δείχνουν τους πρώτους δείκτες που αυτές συναντώνται. Η `unique` θα μας επιστρέψει τα μοναδικά στοιχεία του πίνακα, δεν θα συμπεριλάβει δηλαδή τα διπλότυπα.

In [ ]:
import numpy as np
a = np.array([3, 1, 4, 1, 4, 5, 2, 9, 2])
np.min(a),np.max(a),np.argmin(a),np.argmax(a),np.unique(a)

Η τυπική απόκλιση:
$$
\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (x_i - \mu)^2}
$$
δίνεται από την `std`

In [ ]:
print(np.std(arr))

Το p-οστό εκατοστημόριο ενός συνόλου είναι εκείνη η τιμή, η οποία, όταν οι τιμές διαταχθούν σε αύξουσα σειρά, έχει από αριστερά της το p% των δεδομένων και από δεξιά της το υπόλοιπο (100-p)%. Δίνεται από την `percentile`.

In [ ]:
np.percentile(arr, [25, 50, 75])

Κάποιες βασικές λειτουργίες μπορούν να επιτευχθούν με τον επόμενο τρόπο κλήσης. Ο τρόπος αυτός επιτρέπει την εύκολη κλήση για μέρος των πινάκων.

In [20]:
arr = np.array([3,5,4,9]);arr.sum(),arr.prod(),arr[:2].mean()

(21, 540, 4.0)

## Εσωτερικό γινόμενο διανυσμάτων: Η συνάρτηση dot

Η συνάρτηση `dot` της NumPy υπολογίζει το εσωτερικό γινόμενο δύο διανυσμάτων. Όταν οι παράμετροι είναι αριθμοί και όχι διάνυσμα το αποτέλεσμα είναι το γινόμενό τους.

In [ ]:
np.dot(4,5)

**Παράδειγμα**

Θα δημιουργήσουμε τους πίνακες $x = \begin{bmatrix} 0 & 1 & 2 & 3 \end{bmatrix}$ και $y =\begin{bmatrix}5 & 6 & 7 & 8\end{bmatrix}$. Το εσωτερικό τους γινόμενο υπολογίζεται ως: $\text{inner}(x, y) = (0 \cdot 5) + (1 \cdot 6) + (2 \cdot 7) + (3 \cdot 8)= 0 + 6 + 14 + 24 = 44$.


In [21]:
x = np.arange(4)
y = np.arange(4) + 5
x,y

(array([0, 1, 2, 3]), array([5, 6, 7, 8]))

In [22]:
np.inner(x,y),np.dot(x,y)

44

Προγραμματιστικά θα μπορούσε να υπολογιστεί ως εξης:

In [ ]:
sum(x[i] * y[i] for i in range(len(x)))

H `dot` είναι συνάρτηση της NumPy, αλλά και **μέθοδος** του array της NumPy η οποία μπορεί να εφαρμοστεί σε διάνυσμα ως εξής:

In [ ]:
x.dot(y), y.dot(x)

**Παράδειγμα** Ο συντελεστής συσχέτισης του Pearson

Θα παράξουμε δύο πίνακες 5 τυχαίων αριθμών και θα υπολογίσουμε τον συντελεστή συσχέτισης του Pearson που υπολογίζεται ως εξης:

$$
r_{xy} = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^{n}(x_i - \bar{x})^2}\sqrt{\sum_{i=1}^{n}(y_i - \bar{y})^2}}
$$
Όπου:

- n είναι το μέγεθος του δείγματος

- $x_i$, $y_i$ είναι τα δεδομένα σημεία για κάθε i.

- $\bar{x} $=$ \frac{1}{n}\sum{x_i}$ ο μέσος όρος του δείγματος για τα x και αντίστοιχα για το $\bar{y}$

Η NumPy υλοποιεί τον  συντελεστή Pearson μέσω της συνάρτησης `corrcoef`, η οποία επιστρέφει τα αποτελέσματα με τη μορφή πίνακα. Θα γίνει σύγκριση μεταξύ των δύο συντελεστών.

In [25]:
x = np.random.rand(5)
y = np.random.rand(5)
# Μέσοι όροι δειγμάτων x, y
x_avg = np.average(x)
y_avg = np.average(y)
x_2 = np.inner(x-x_avg, x-x_avg)  # Εναλλακτικά dot
y_2 = np.inner(y-y_avg, y-y_avg)  # Εναλλακτικά dot
r_xy = np.dot(x-x_avg, y-y_avg)/np.sqrt(x_2*y_2)
# Σύγκριση με τον τελεστή Pearson της numpy
r_xy,np.corrcoef(x,y)

(0.35612215767467637,
 array([[1.        , 0.35612216],
        [0.35612216, 1.        ]]))

<a id="numpy_more"></a>
# Πίνακες περισσότερων διαστάσεων

## Δημιουργία

### Λίστα

Όπως και στην περίπτωση των διανυσμάτων, πίνακες διάστασης μεγαλύτερης από 1 δημιουργούνται από αντίστοιχες λίστες.

In [ ]:
m = np.array([[1,2],[2,3]]);m

Η μέθοδος `flatten` μπορεί να μετατρέψει τον πίνακα από πολλών διαστάσεων σε διάνυσμα.

In [ ]:
m.flatten()

Ένας πίνακας μπορεί να έχει και παραπάνω από 2 διαστάσεις. Υπάρχει όριο στις διαστάσεις, συνήθως 32.

In [ ]:
d3 = np.array(
    [[[1,2,1,2], [3,4,1,2]],
     [[5,4,1,2], [3,1,1,2]],
     [[5,7,1,2], [9,1,1,2]]])
d3

Η `meshgrid` δημιουργεί πλέγματα όπως αυτά ορίζονται από τους πίνακες ή λίστες που δέχεται ως παράμετρο.

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
X,Y

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]]))

### Μηδέν ή ένα

Οι μέθοδοι `zeros`, `ones`, αν δεχτούν πλειάδα αντί για απλό αριθμό, δημιουργούν πίνακα με περισσότερες διαστάσεις αντί για διάνυσμα.

In [ ]:
z = np.zeros((2,3))
print(z)

In [ ]:
ones = np.ones((1,3))
print(ones)

Η `full` γεμίζει έναν πίνακα διαστάσεων της πλειάδας της πρώτης παραμέτρου με την τιμή της δεύτερης παραμέτρου. Αν η πρώτη παράμετρος είναι ακέραιος θα δημιουργήσει διάνυσμα.

In [ ]:
np.full((3,3),3.14),np.full(4,1.61)

Η `np.eye` δημιουργεί μοναδιαίο πίνακα.

In [ ]:
np.eye(3)

### Τυχαία στοιχεία

Ακολουθούν τρόποι δημιουργίας πινάκων τυχαίων αριθμών διάστασης μεγαλύτερης από 1. Περιλαμβάνουν πλειάδες με το σχήμα του παραγόμενου πίνακα.

Ομοιόμορφα κατανεμημένα αριθμοί στο διάστημα [0,1) δημιουργουνται με την `rand`.

In [ ]:
np.random.rand(2,3)

Κανονική κατανομή με μέσο όρο 0 και τυπική απόκλιση 1 έχουν οι τυχαίοι αριθμοί που προκύπτουν από την `randn`.

In [ ]:
np.random.randn(2,4)

Για να θέσουμε διαφορετικές τιμές στον μέσο όρο και την τυπική απόκλιση μίας κανονικής κατανομής χρησιμοποιούμε την `normal` με τις παραπάνω τιμές ως πρώτες παραμέτρους. Ακολουθεί ένα `tuple` με τις διαστάσεις του τυχαίου πίνακα που θα προκύψει.

In [ ]:
np.random.normal(3,2,(2,4))

Η `randint` παράγει τυχαίους ακεραίους στο διάστημα που δίνεται με τις δύο πρώτες παραμέτρους. Το σχήμα του πίνακα δίνεται με το `tuple` που ακολουθεί.

In [ ]:
np.random.randint(1,7,size=(3,4))

## Πρόσβαση σε στοιχεία

Η πρόσβαση σε μενονωμένα στοιχεία γίνεται με τρόπο ανάλογο με τους μονοδιάστατους πίνακες NumPy, αλλά και τις δομές της Python.

Ακολουθεί ο τρόπος δεικτοδότησης ενός πίνακα 3x4. 
$$
\begin{array}{|c|c|c|c|c|}
\hline
 & \textbf{0} & \textbf{1} & \textbf{2} & \textbf{2} \\
\hline
\textbf{0} & (0,0) & (0,1) & (0,2) & (0,3) \\
\hline
\textbf{1} & (1,0) & (1,1) & (1,2) & (1,3) \\
\hline
\textbf{2} & (2,0) & (2,1) & (2,2) & (2,3) \\
\hline
\end{array}
$$


**Παράδειγμα**

Δημιουργούμε διάνυσμα _a_ στοιχείων 1,2,...,12 και το μετατρέπουμε σε πίνακα 3Χ4. Στην συνέχεια εμφανίζουμε:

1. a: Όλον τον πίνακα

2. a[1,2]: 2η γραμμή - δείκτης 1, 3η στήλη - δείκτης 2

3. a[-1,-1]: τελευταία γραμμή, τελευταία στήλη

In [ ]:
a = np.arange(1,13).reshape((3,4))

print(a)
print(a[1,2])
print(a[-1,-1])

Ο ίδιος τρόπος που χρησιμοποιείται στα διανύσματα για επιλογές περισσότερων στοιχείων, το σχήμα δηλαδή start:stop:step μπορεί να λειτουργήσει και στις περισσότερες διαστάσεις αρκεί να χωρίσουμε με κόμμα. Με τον τρόπο αυτό επιλέγουμε όποιο υποσύνολο του πίνακα επιθυμούμε.

- $a[0:2,1:3]$

$$
\begin{array}{|c|c|c|c|}
\hline
1 & 2 & 3 & 4 \\ \hline
5 & 6 & 7 & 8 \\ \hline
9 & 10 & 11 & 12 \\ \hline
\end{array}
\quad \Rightarrow \quad
\begin{array}{|c|c|}
\hline
2 & 3 \\ \hline
6 & 7 \\ \hline
\end{array}
$$

- $a[:,:2]$

$$
\begin{array}{|c|c|c|c|}
\hline
1 & 2 & 3 & 4 \\ \hline
5 & 6 & 7 & 8 \\ \hline
9 & 10 & 11 & 12 \\ \hline
\end{array}
\quad \Rightarrow \quad
\begin{array}{|c|c|}
\hline
1 & 2 \\ \hline
5 & 6 \\ \hline
9 & 10 \\ \hline
\end{array}
$$


In [ ]:
a[0:2,1:3],a[:,:2]

<a id="numpy_more_shape"></a>
## Διάταξη στοιχείων

Οι πίνακες της NumPy διαθέτουν την ιδιότητα `shape` η οποία περιγράφει την διάταξη των στοιχείων σε κάθε διάσταση. Η διάταξη καθορίζεται από μία πλειάδα, `tuple`. Σε περίπτωση διανύσματος, η πλειάδα περιέχει ένα στοιχείο. 

Οι πίνακες της NumPy παρέχουν τις ιδιότητες:

 - `shape` η οποία περιγράφει την διάταξη των στοιχείων σε κάθε διάσταση. Η διάταξη καθορίζεται από μία πλειάδα, `tuple`. Σε περίπτωση διανύσματος η πλειάδα περιέχει ένα στοιχείο. Η εμφάνιση των διαστάσεων γίνεται από έξω προς τα μέσα.
 
 - `ndim` που περιγράφει τον αριθμό διαστάσεων των στοιχείων.
 
 - `size` που δίνει τον συνολικό αριθμό στοιχείων του πίνακα
 
 - `itemsize` που μας δείχνει το μέγεθος σε bytes ενός στοιχείου του πίνακα
 
 - `nbytes` το μέγεθος σε bytes όλου του πίνακα
 
 - `data` τη διεύθυνση μνήμης στην οποία είναι αποθηκευμένος ο πίνακας

In [ ]:
print(m.shape)
print(m.ndim)
print(m.size)
print(m.itemsize)
print(m.nbytes)
print(m.nbytes/m.itemsize==m.size)
print(m.data)

In [ ]:
v = np.array([1,2,3,4])
v.shape,v.ndim,v.size

In [ ]:
d3.shape,d3.ndim,d3.size

## reshape

Η `numpy.reshape` δημιουργεί ένα νέο σχήμα πίνακα με βάση μια πλειάδα, χωρίς να τροποποιεί τα δεδομένα του πίνακα.
- (12,) &#8594; (3,4)

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\
\hline
\end{array}
\quad \Rightarrow \quad
\begin{array}{|c|c|c|c|}
\hline
1 & 2 & 3 & 4 \\ \hline
5 & 6 & 7 & 8 \\ \hline
9 & 10 & 11 & 12 \\ \hline
\end{array}
$$

- (12,) &#8594; (2,6)

$$
\begin{array}{|c|c|c|c|c|c|c|c|c|c|c|c|}
\hline
1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 & 11 & 12 \\
\hline
\end{array}
\quad \Rightarrow \quad
\begin{array}{|c|c|c|c|c|c|}
\hline
1 & 2 & 3 & 4 & 5 & 6 \\ \hline
7 & 8 & 9 & 10 & 11 & 12 \\ \hline
\end{array}
$$

In [ ]:
alpha = np.arange(1,13);alpha

In [ ]:
beta = alpha.reshape((3,4))
beta

Η `reshape` είναι μέθοδος, η οποία εφαρμόζεται σε αντικείμενα `array`, αλλά και με παραμέτρους πίνακα και ζητούμενο σχήμα. Η επόμενη εντολή είναι ισοδύναμη με την προηγούμενη. Εφαρμόζουμε απλά διαφορετικό σχήμα.

In [ ]:
gamma = np.reshape(alpha,(2,6));gamma

Η μέθοδος `reshape` δρα πάνω σε ένα αντικείμενο `array` χωρίς να το μεταβάλλει. Το νέο σχήμα προκύπτει μέσα από την επιστρεφόμενη τιμή της μεθόδου.

In [ ]:
alpha

Μπορούμε να αφήσουμε μια διάσταση απροσδιόριστη κατά την κλήση της `reshape`, δίνοντας την τιμή -1, οπότε το κατάλληλο πλήθος στοιχείων θα υπολογιστεί αυτόματα δημιουργώντας σχήμα 6x2.

In [ ]:
delta = alpha.reshape((6,-1));delta

## `transpose`

Όπως και η `reshape`, η `transpose` δημιουργεί *όψεις* των ίδιων εσωτερικών δεδομένων. 

$$
\begin{bmatrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{bmatrix}
\quad \Rightarrow \quad
\begin{bmatrix} 1 & 5 & 9 \\ 2 & 6 & 10 \\ 3 & 7 & 11 \\ 4 & 8 & 12 \end{bmatrix}
$$

In [ ]:
a = np.arange(1,13)
print('a:')
print(a)
b = a.reshape((3,4))
print('b:')
print(b)
c = b.transpose()
print('c:')
print(c)

## `diag`

Η `diag` είτε δημιουργεί έναν διαγώνιο πίνακα από διάνυσμα είτε επιστρέφει τη διαγώνιο ενός πίνακα

$$
\begin{array}{|c|c|c|c|}
\hline
1 & 2 & 3 & 4 \\
\hline
5 & 6 & 7 & 8 \\
\hline
9 & 10 & 11 & 12 \\
\hline
13 & 14 & 15 & 16 \\
\hline
\end{array}
\quad
\Rightarrow
\quad
\begin{array}{|c|c|c|c|}
\hline
1 & 6 & 11 & 16 \\
\hline
\end{array}
$$

$$
\begin{array}{|c|c|c|c|}
\hline
1 & 6 & 11 & 16 \\
\hline
\end{array}
\quad
\Rightarrow
\quad
\begin{array}{|c|c|c|c|}
\hline
1 & 0 & 0 & 0 \\
\hline
0 & 6 & 0 & 0 \\
\hline
0 & 0 & 11 & 0 \\
\hline
0 & 0 & 0 & 16 \\
\hline
\end{array}
$$


In [ ]:
a = np.arange(1,17).reshape((4,4))
print(a)
print('->')
b = np.diag(a)
print(b)

In [ ]:
print(b)
print('->')
c = np.diag(b)
print(c)

**Παράδειγμα**

Να φτιαχτεί ένας πίνακας NumPy ο οποίος περιγράφει μια σκακιέρα με ακέραιους, 0,1.
$$
\begin{bmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1 \\
1 & 0 & 1 & 0 & 1 & 0 & 1 & 0 \\
0 & 1 & 0 & 1 & 0 & 1 & 0 & 1
\end{bmatrix}
$$

Αρχικά δημιουργούμε έναν πίνακα 8x8 από 0. Ορίζουμε τα στοιχεία του πίνακα ως ακέραια μέσω της `dtype`.

In [27]:
a = np.zeros((8,8), dtype=int);a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

Στη συνέχεια, δίνουμε στα στοιχεία κάθε δεύτερης γραμμής την τιμή 1, εναλλάξ για κάθε δεύτερη στήλη.

In [28]:
a[::2, ::2] = 1;a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

Τέλος, δίνουμε, όπως και πριν, στα στοιχεία κάθε δεύτερης γραμμής εναλλάξ για κάθε δεύτερη στήλη, την τιμή 1, ξεκινώντας όμως από τη δεύτερη γραμμή και δεύτερη στήλη.

In [29]:
a[1::2,1::2] = 1;a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# Αντίγραφα και όψεις πινάκων

Οι πίνακες της NumPy συμπεριφέρονται ως τροποποιήσιμα, **mutable**, αντικείμενα. Έστω ο πίνακας:

In [ ]:
a_matrix = np.arange(16).reshape((4,4))
a_matrix

Μια εντολή ανάθεσης της μορφής:

In [ ]:
b_matrix = a_matrix

δεν δημιουργεί έναν νέο πίνακα, αλλά μια αναφορά στον αρχικό, _a_matrix_. Με βάση την παραπάνω ανάθεση, η αλλαγή στοιχείου του _b_matrix_ συνεπάγεται την αλλαγή των στοιχείων του _a_matrix_.

In [ ]:
b_matrix[0][0] = -100
print(a_matrix[0][0])

Τα δύο ονόματα αναφέρονται στο ίδιο αντικείμενο.

In [ ]:
b_matrix is a_matrix

Σε συλλογές της python όπως οι λίστες, η a=b[:] Θα δημιουργήσει ένα ρηχό αντίγραφο, **shallow copy**.

In [ ]:
L1 = [1, 2, 3]
L2 = L1[:]
L2[0]=100
L1,L2

Αντίθετα στην NumPy η ίδια σύνταξη θα δημιουργήσει μία νέα όψη, **view** στα ίδια δεδομένα.

In [ ]:
a1 = np.array([1, 2, 3])
a2 = a1[:]
a2[0]=100
a1,a2

**Παράδειγμα**

Από τον αρχικό πίνακα:
$$
a =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

Δημιουργούμε ένα view $b$, το οποίο περιλαμβάνει τη 2η και 3η γραμμή, καθώς και τη 2η και 3η στήλη:

$$
b =
\begin{bmatrix}
6 & 7 \\
10 & 11
\end{bmatrix}
$$

Αν τροποποιήσουμε το $b$ ώστε όλα τα στοιχεία του να γίνουν 100:

$$
b =
\begin{bmatrix}
100 & 100 \\
100 & 100
\end{bmatrix}
$$

τότε ο αρχικός πίνακας $a$ αλλάζει επίσης:

$$
a =
\begin{bmatrix}
1 & 2  & 3  & 4  \\
5 & 100 & 100 & 8  \\
9 & 100 & 100 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

In [ ]:
a = np.arange(1, 17).reshape(4, 4)
print("Αρχικός πίνακας a:")
print(a)

# Δημιουργία view
b = a[1:3, 1:3]
print("\nView b:")
print(b)

# Τροποποίηση του view
b[:] = 100
print("\nΜετά την αλλαγή στο b:")
print(b)
print("a:")
print(a)  # Παρατηρούμε ότι αλλάζει και ο αρχικός πίνακας!

Αν θέλουμε να δημιουργήσουμε αντίγραφο του αρχικού πίνακα, χρησιμοποιούμε τη μέθοδο `copy` η οποία επιστρέφει έναν νέο πίνακα αντιγράφοντας τα στοιχεία του αρχικού. Αλλάζοντας δεδομένα στον ένα πίνακα, ο άλλος πίνακας μένει ανεπηρέαστος.

In [ ]:
a = np.arange(1, 17).reshape(4, 4)
c = a.copy()
a[0][0] = 100
a, c

# Πολλαπλασιασμός Πινάκων

## matmul, @

Ο πολλαπλασιασμός πινάκων γίνεται με τη συνάρτηση `matmul` ή, ισοδύναμα, τον τελεστή `@`.

**Παράδειγμα**

Στο παρακάτω παράδειγμα,  ο  $4\times3$  πίνακας 
$\left(\begin{matrix}2&1&1\\1&3&1\\1&1&4\\1&1&1\end{matrix}\right)$ πολλαπλασιάζεται με τον $3\times2$ πίνακα $\left(\begin{matrix}1&1\\1&1\\1&1\end{matrix}\right)$ με αποτέλεσμα 
$\left(\begin{matrix}4&4\\5&5\\6&6\\3&3\end{matrix}\right)$

In [ ]:
a = np.ones((4,3))
a[0][0]=2
a[1][1]=3
a[2][2]=4
print('a:')
print(a)
b = np.ones((3,2))
print('b:')
print(b)
print('a @ b:')
print(a @ b)
print('np.matmul(a,b):')
print(np.matmul(a,b))

 ## `dot`

 Εναλλακτικά, ο πολλαπλασιασμός πινάκων μπορεί να πραγματοποιηθεί με τη συνάρτηση `dot`.

**Παράδειγμα**

Θα εφαρμόσουμε την επόμενη πράξη με χρήση της `dot`.
$$
\begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5
\end{bmatrix}
\cdot
\begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5 \\
6 & 7 & 8
\end{bmatrix}
=
\begin{bmatrix}
15 & 18 & 21 \\
42 & 54 & 66
\end{bmatrix}
$$



In [ ]:
a = np.arange(6)
a = a.reshape((2,3))
print('a:')
print(a)
b = np.arange(9)
b = b.reshape((3,3))
print('b:')
print(b)
print('np.dot(a,b):')
print(np.dot(a,b))

## Πίνακας επί διάνυσμα (πίνακας-στήλη)

Ένας πίνακας είναι δυνατόν να πολλαπλασιαστεί με διάνυσμα. Το αποτέλεσμα εξαρτάται από τη μορφή του διανύσματος.

Για παράδειγμα εάν το διάνυσμα δοθεί στη μορφή πίνακα-στήλης, το αποτέλεσμα θα είναι αντίστοιχα σε μορφή πίνακα-στήλης:
$$\left(\begin{matrix}0&1&2&3\\4&5&6&7\\8&9&10&11\end{matrix}\right) \times \left(\begin{matrix}0\\1\\2\\3\end{matrix}\right) = \left(\begin{matrix}14\\38\\62\end{matrix}\right)$$

In [ ]:
a = np.arange(12)
a = a.reshape((3,4))
print(a)

b = np.arange(4)
b = b.reshape((4,1))
print(b)

c = np.dot(a,b)
print(c)
a.shape,'x',b.shape,'->',c.shape

**Παράδειγμα**

$$
c =
\begin{bmatrix} 0 & 1 \\ 2 & 3 \end{bmatrix}  
\cdot  
\begin{bmatrix} 1 & 2 \end{bmatrix}  
=  
\begin{bmatrix} (0 \cdot 1 + 1 \cdot 2) \\ (2 \cdot 1 + 3 \cdot 2) \end{bmatrix}  
=  
\begin{bmatrix} 2 & 8 \end{bmatrix}
$$

In [ ]:
a = np.arange(4)
a = a.reshape((2,2))
print('a:')
print(a)

b = np.array([1,2])
print('b:')
print(b)

c = np.dot(a,b)
print('c:')
print(c)
a.shape,'x',b.shape,'->',c.shape

**Παράδειγμα**

 Έστω ο πίνακας-στήλη $\textbf{x} = \left(\begin{matrix}1 \\2 \\3\\4\end{matrix}\right)$. Να υπολογιστούν τα γινόμενα $\textbf{x}^T \textbf{x}$ και $\textbf{x}\textbf{x}^T$ με τη χρήση της NumPy.

Το διάνυσμα $\textbf{x}$ γράφεται ως:

In [ ]:
x = np.arange(1,5).reshape((4,1));x # ή, ισοδύναμα, .reshape((-1,1))

Οπότε το πρώτο γινόμενο $\textbf{x}^T \textbf{x}$  υπολογίζεται ως

In [ ]:
x.transpose().dot(x)

To  $\textbf{x}\textbf{x}^T$ υπολογίζεται ως

In [ ]:
x.dot(x.transpose())

Αντί για τη μέθοδο `transpose` μπορούμε, εναλλακτικά, να χρησιμοποιήσουμε το χαρακτηριστικό `T` ενός πίνακα `numpy` οπότε, με τον τελεστή `@` αντί της `dot` παίρνουμε το  ίδιο αποτέλεσμα:

In [ ]:
x @ x.T

# Άλλες εντολές

## `delete`

Η συνάρτηση `delete` δέχεται ως παράμετρο έναν πίνακα και επιστρέφει έναν νέο πίνακα, διαγράφοντας στοιχεία κατά την κατεύθυνση ενός άξονα του αρχικού (π.χ. γραμμής ή στήλης). Για έναν διασδιάστο πίνακα, η μορφή 

```Python
delete(array, αριθμός, άξονας)
```
διαγράφει στον πίνακα `array` τη γραμμή ή στήλη `αριθμός`, αν η τιμή `άξονας` είναι 0 ή 1, αντίστοιχα.

In [ ]:
a = np.arange(12).reshape((3,4));a

Διαγραφή της τρίτης γραμμής του πίνακα _a_:

In [ ]:
np.delete(a, 2, 0)

Διαγραφή της δεύτερης στήλης του πίνακα _a_:

In [ ]:
np.delete(a,1,1)

**Παράδειγμα** Laplace expansion
    
Μπορούμε με χρήση της `delete` να υπολογίσουμε την ορίζουσα ενός τετραγωνικού πίνακα με αναδρομική διαδικασία υπολογισμού της ορίζουσας ενός πίνακα με τη γνωστή μέθοδο <a href="https://en.wikipedia.org/wiki/Laplace_expansion">Laplace expansion</a>. 
$\det(A) = \sum_{j=1}^{n} (-1)^{i+j} a_{ij} m_{ij}$

Με τη συνάρτηση `delete` δημιουργούμε τους υποπίνακες της μεθόδου, διαγράφοντας μια γραμμή και στήλη κάθε φορά.

In [ ]:
import numpy as np
mem = []
def del_rc(a,i,j):
    d = np.delete(a,i,0) # Διαγραφή γραμμής i
    d = np.delete(d,j,1) # Διαγραφή στήλης j
    return d

def my_determinant(a):
    if (len(a) == 1):
        return a[0][0]
    return sum([(-1) ** i * a[i][0] * my_determinant(del_rc(a, i, 0)) for i in range(len(a))])
 
my_matrix = np.array([[1,2,3],
    [3,2,1],
    [2,1,3]])
my_determinant(my_matrix)


Η  μέθοδος Laplace expansion δεν είναι αποδοτική και δεν χρησιμοποιείται στην πράξη για τον υπολογισμό της ορίζουσας. Επιπλέον, η αναδρομική υλοποίηση που δίνουμε παραπάνω πάσχει από το πρόβλημα που συναντήσαμε στους αλγορίθμους δυναμικού προγραμματισμού: Επαναληπτικούς υπολογισμούς των ίδιων υπο-οριζουσών. Για την αντιμετώπιση αυτού το προβλήματος, μπορεί να εφαρμοστεί κι εδώ η λύση του **memoization**.

## Συνένωση, διαχωρισμός

Η συνένωση δύο ή περισότερων πινάκων μπορεί να επιτευχθεί με μία από τις μεθόδους `concatenate`, `vstack`, `hstack`. Στην περίπτωση παραπάνω από μίας διάστασης στους πίνακες επιλέγεται ο άξονας ως προς τον οποίο θα γίνει η συνένωση, εξορισμού ο άξονας 0.

Σημείωση: Σε έναν πίνακα δύο διαστάσεων μπορεί κανείς να σκέφτεται τις γραμμές ώς άξονα 0 και τις στήλες ώς άξονα 1.

**Παράδειγμα**

Θα εφαρμόσουμε την `concatenate` στους πίνακες:
$v_1 = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix}$,$v_2 = \begin{bmatrix} 10 & 20 & 30 \end{bmatrix}$

$$
\begin{array}{v_3}
\begin{bmatrix} 1 & 2 & 3 \end{bmatrix} + 
\begin{bmatrix} 10 & 20 & 30 \end{bmatrix}
\Rightarrow
\begin{bmatrix} 1 & 2 & 3 & 10 & 20 & 30 \end{bmatrix}
\end{array}
$$

Στη συνέχεια, εκτός από τους $v_1$ και $v_2$ θα προσθέσουμε και τον $v_3 = \begin{bmatrix} 100 & 200 & 300 \end{bmatrix}$

$$
\begin{array}{c}
\begin{bmatrix} 1 & 2 & 3 \end{bmatrix} + 
\begin{bmatrix} 10 & 20 & 30 \end{bmatrix} +
\begin{bmatrix} 100 & 200 & 300 \end{bmatrix}
\Rightarrow
\begin{bmatrix} 1 & 2 & 3 & 10 & 20 & 30 & 100 & 200 & 300 \end{bmatrix}
\end{array}
$$

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([10, 20, 30])
v3 = np.array([100, 200, 300])
v4 = np.concatenate([v1,v2])
print("v4:")
print(v4)
v5 = np.concatenate([v1,v2,v3])
print("v5:")
print(v5)

**Παράδειγμα**

Στον πίνακα $
m =
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
$
θα εφαρμόσουμε την `concatenate` κατά μήκος του άξονα 0 του m με τον εαυτό της:

$$
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
$$

Στον ίδιο πίνακα θα εφαρμόσουμε την `concatenate` κατά μήκος του άξονα 1:

$$
\begin{bmatrix} 
1 & 2 & 3 & 1 & 2 & 3 \\ 
4 & 5 & 6 & 4 & 5 & 6 
\end{bmatrix}
$$


In [ ]:
m = np.arange(1,7).reshape((2,3))
print("Στον άξονα 0:")
print(np.concatenate([m,m]))
print("Στον άξονα 1:")
print(np.concatenate([m,m], axis=1))

Μερικές φορές είναι πιο ξεκάθαρο να χρησιμοποιηθούν οι μέθοδοι `hstack`, `vstack` για οριζόντιo και κατακόρυφο "στοίβαγμα" αντίστοιχα.

**Παράδειγμα**

Στους πίνακες 
$
v_1 =
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
$
και
$
v_2 =
\begin{bmatrix} 
10 & 20 & 30 
\end{bmatrix}
$
εφαρμόζοντας κάθετο "στοίβαγμα" θα προκύψει ο πίνακας:
$
v_3 =
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
10 & 20 & 30 
\end{bmatrix}
$

Στην συνέχεια θα εφαρμόσουμε οριζόντιο "στοίβαγμα" στον πίνακα 
$
v_1 =
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
$
και
$
v_4 =
\begin{bmatrix} 
100 \\ 
200 
\end{bmatrix}
$
. Θα προκύψει ο πίνακας:

$
v_5 =
\begin{bmatrix} 
1 & 2 & 3 & 100 \\ 
4 & 5 & 6 & 200 
\end{bmatrix}
$


In [ ]:
v1 = np.arange(1,7).reshape((2,3))
v2 = np.arange(10,40,10)
v3 = np.vstack([v1,v2])
v4 = np.arange(100,300,100).reshape(2,1)
v5 = np.hstack([v1,v4])
print('v1:')
print(v1)
print('v2:')
print(v2)
print('v3:')
print(v3)
print('v4:')
print(v4)
print('v5:')
print(v5)

Αντίστροφη πράξη της συνένωσης είναι ο διαχωρισμός που υλοποιείται με τις μεθόδους `split`, `hsplit`, `vsplit`. Οι μέθοδοι δέχονται ως παράμετρο, εκτός από την προς διαχωρισμό λίστα, τα σημεία στα οποία αυτή θα διαχωριστεί. Σημειώνεται ότι N σημεία διάσπασης δημιουργούν N+1 πίνακες.

**Παράδειγμα**

Στο παράδειγμα η np.split(s, [3, 7]) αν εφαρμοστεί στον πίνακα s = [1, 2, 3, 10, 20, 30, 40, 100, 200] με 2 σημεία διάσπασης θα δημιουργήσει τρεις πίνακες:

$_s1 = [1, 2, 3], \quad s_2 = [10, 20, 30, 40], \quad s_3 = [100, 200]$

In [ ]:
s = [1, 2, 3, 10, 20,30,40, 100,200]
s1,s2,s3 = np.split(s, [3, 7])
print(s1,s2,s3)

Με παρόμοια λογική δουλεύουν οι μέθοδοι `vsplit`, `hsplit`.

**Παράδειγμα**

Έστω αρχικός πίνακας `d` είναι ένας $4 \times 4$ πίνακας:

$$
d =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8 \\
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

Ο κάθετος διαχωρισμός με `np.vsplit(d, [2])`
Χωρίζει τον πίνακα σε δύο μέρη:
$$
dup =
\begin{bmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8
\end{bmatrix}
\quad
ddown =
\begin{bmatrix}
9 & 10 & 11 & 12 \\
13 & 14 & 15 & 16
\end{bmatrix}
$$

---

Ο οριζόντιος διαχωρισμός με `np.hsplit(d, [2])`
Χωρίζουμε τον πίνακα σε δύο μέρη:
$$
dleft =
\begin{bmatrix}
1 & 2 \\
5 & 6 \\
9 & 10 \\
13 & 14
\end{bmatrix}
\quad
dright =
\begin{bmatrix}
3 & 4 \\
7 & 8 \\
11 & 12 \\
15 & 16
\end{bmatrix}
$$


In [ ]:
d = np.arange(1,17).reshape((4, 4))
print('d:')
print(d)
dup,ddown = np.vsplit(d, [2])
dleft,dright = np.hsplit(d, [2])
print('dup:')
print(dup)
print('ddown:')
print(ddown)
print('dleft:')
print(dleft)
print('dright:')
print(dright)

#  NumPy Αρχεία

Οι πίνακες της βιβλιοθήκης NumPy μπορούν να αποθηκευτούν σε κατάλληλα αρχεία, τόσο κειμένου όσο και δυαδικά. Έτσι θα μπορούν να ανακτηθούν στη συνέχεια.

## Αρχεία κειμένου

Η συνάρτηση `savetxt` επιτρέπει την αποθήκευση ενός πίνακα NumPy σε μορφή κειμένου. 

In [ ]:
import numpy as np
a = np.arange(100)
np.savetxt("mynumpyarray.txt",a)

Αντίστοιχα, η `loadtxt` διαβάζει τα στοιχεία ενός πίνακα από ένα αρχείο κειμένου.

In [ ]:
b = np.loadtxt("mynumpyarray.txt")
print(np.average(b))

Οι παραπάνω συναρτήσεις εφαρμόζονται και σε πίνακες διάστασης μεγαλύτερης του 1.

In [ ]:
c = np.ones((5,2))
np.savetxt("ones.dat", c)

## Δυαδικά αρχεία

Η εργασία με αρχεία κειμένου στο πλαίσιο της NumPy είναι σκόπιμη όταν ο όγκος των δεδομένων δεν είναι ιδιαίτερα μεγάλος ή όταν θέλουμε να έχουμε μια εναλλακτική εικόνα των δεδομένων, π.χ. με τη χρήση προγραμμάτων λογιστικών φύλλων (Excel, LibreOffice, κλπ). 

Σε περιπτώσεις μεγάλου όγκου δεδομένων η εργασία γίνεται με *δυαδικά* αρχεία με τη χρήση των συναρτήσεων`load()` και `save()` της numpy.

Η συνάρτηση `save()` επιτρέπει την αποθήκευση ενός πίνακα numpy σε δυαδική μορφή.

In [ ]:
a = np.arange(100)
np.save("afile.npy",a)

In [ ]:
b = np.load("afile.npy");b

Εναλλακτικά, είναι δυνατόν να διαχειριστούμε αρχεία της NumPy τα οποία ανοίγουν με κατάλληλη χρήση της συνάρτησης `open()`. Στην περίπτωση αυτή, οι `load()` και `save()` δεν δέχονται ως παράμετρο το όνομα του αρχείου, αλλά ένα αντικείμενο αρχείου, όπως στο παράδειγμα που ακολουθεί

In [ ]:
with open('test.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))
    np.save(f, np.array([1, 3]))
with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
a, b

# Απόδοση

## Vectorization

Μία διαδικασία υπολογισμού, όπως κάποιο άθροισμα σαν αυτό του παραδείγματος που ακολουθεί, χρησιμοποιεί βρόχο `for` για να διατρέξει κάθε στοιχείο του πίνακα υπολογίζοντας κάθε στοιχείο διαδοχικά. Ο ίδιος υπολογισμός μπορεί να υλοποιηθεί με πίνακες της `NumPy` χωρίς την πρόσβαση στα επιμέρους στοιχεία των πινάκων. Αυτή η μέθοδος υλοποίησης ονομάζεται **vectorization** και είναι ιδιαίτερα αποδοτική, καθώς αξιοποιεί τις βελτιστοποιημένες διαδικασίες της βιβλιοθήκης `numpy`.

**Παράδειγμα**
   
  Θα δημιουργήσουμε δύο τυχαίους πίνακες με 10.000.000 στοιχεία ο καθένας και θα βρούμε το άθροισμα των γινομένων όλων των στοιχείων. Θα χρονομετρήσουμε την διαδικασία.

Δημιουργία πινάκων

In [30]:
N = 10_000_000
a = np.random.rand(N,1) 
b = np.random.rand(N,1)

In [31]:
import time
start = time.time()
s = 0 
for i in range(N): 
  s = s + a[i] * b[i]
end = time.time()
print('Αποτέλεσμα:', s)
print('Χρόνος:', end - start,'δευτερόλεπτα')

Αποτέλεσμα: [2499370.48372115]
Χρόνος: 20.65992784500122 δευτερόλεπτα


In [32]:
start = time.time()
s = np.sum(a * b)
end = time.time()
print('Αποτέλεσμα:', s)
print('Χρόνος:', end - start,'δευτερόλεπτα')

Αποτέλεσμα: 2499370.48372103
Χρόνος: 0.05435347557067871 δευτερόλεπτα


**Παράδειγμα**

Θα πολλαπλασιάσουμε δύο πίνακες με τυχαία στοιχεία με μεθόδους python και με χρήση NumPy και θα συγκρίνουμε τον χρόνο σε κάθε περίπτωση. Εμφανίζουμε και ένα στοιχείο του γινομένου.

In [33]:
n = 150
A = [[np.random.rand() for _ in range(n)] for _ in range(n)]
B = [[np.random.rand() for _ in range(n)] for _ in range(n)]
start = time.time()
# Δημιουργία άδειου πίνακα
prod = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            prod[i][j] += A[i][k] * B[k][j]
s = np.sum(a * b)
end = time.time()
print('Αποτέλεσμα [0][0]:',prod[0][0])
print('Χρόνος:', end - start,'δευτερόλεπτα')

start = time.time()
prod = np.dot(A, B)
end = time.time()
print('Αποτέλεσμα [0][0]:',prod[0][0])
print('Χρόνος:', end - start,'δευτερόλεπτα')

Αποτέλεσμα [0][0]: 35.49716275641173
Χρόνος: 1.4332866668701172 δευτερόλεπτα
Αποτέλεσμα [0][0]: 35.49716275641173
Χρόνος: 0.047821760177612305 δευτερόλεπτα


## Μνήμη

Μία λίστα python δεν περιέχει τα ίδια τα δεδομένα αλλά δείκτες προς αυτά. Έτσι, όταν διασχίζεται μία λίστα θα πρέπει να αναζητείται η θέση στην μνήμη κάθε αντικειμένου ξεχωριστά. Κάτι τέτοιο οδηγεί σε χαμηλότερη απόδοση. Για παράδειγμα η λίστα L=[2, 3, 3, 1, 4] στην μνήμη θα αποθηκευόταν σαν μία λίστα διευθύνσεων όπως στον επόμενο πίνακα.
| Δείκτης    | Διεύθυνση|
|------------|----------|
| L[0]    | 0x25012  |
| L[1]    | 0x25008  |
| L[2]    | 0x25020  |
| L[3]    | 0x250a8  |
| L[4]    | 0x250a2  |

Στις διευθύνσεις όπου δείχνουν τα στοιχεία του πίνακα θα είναι αποθηκευμένες οι τιμές.

| Address  | Τιμή   |
|----------|--------|
| 0x25008  |   5    |
|   ...    |  ...   |
| 0x25012  |   2    |
|   ...    |  ...   |
| 0x25020  |   3    |
|   ...    |  ...   |
| 0x250a2  |   4    |
|   ...    |  ...   |
| 0x250a8  |   1    |
|   ...    |  ...   |

Από την άλλη μεριά, οι πίνακες της NumPy έχουν σχεδιαστεί ειδικά για λειτουργίες πινάκων με όλους τους τύπους δεδομένων του να είναι πανομοιότυποι, με το ίδιο μέγεθος byte. Αυτό επιτρέπει στα δεδομένα να βρίσκονται σε συνεχόμενες θέσεις μνήμης χωρίς να απαιτούνται δείκτες για κάθε ξεχωριστό στοιχίο. Έτσι γίνεται αποδοτικότερη η διαχείριση κρυφής μνήμης και επιτρέπονται οι **vectorized** υπολογισμοί.

# Προχωρημένη εφαρμογή: Η μέθοδος Jacobi

Επίλυση του συστήματος 
$Α\mathbf{x} = \mathbf{b}$, όπου $A$ πίνακας $m\times n$ και $\textbf{x},\textbf{b}$ διανύσματα με $n$ στοιχεία.

$$
A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nn}
\end{pmatrix}
$$
$$
\mathbf{x} = \begin{pmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{pmatrix}
$$
$$
\mathbf{b} = \begin{pmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{pmatrix}
$$



## Αλγόριθμος

$$
x_i^{(k+1)} = \frac{1}{a_{ii}} \left( b_i - \sum_{\substack{j=1 \\ j \neq i}}^{n} a_{ij}x_j^{(k)} \right),\, i=1,2,...,n, \, \text{για } k\ge 0
$$ 


Επαναληπτική μέθοδος υπολογισμού του διανύσματος x η οποία συγκλίνει αν
$$
|a_{ii}| > \sum_{\substack{j=1 \\ j \neq i}}^{n} |a_{ij}|,\, i =1,2,\ldots,n
$$

## Με χρήση επανάληψης

Μια άμεση υλοποίηση του παραπάνω αλγορίθμου  στη γλώσσα Python είναι η ακόλουθη:

In [ ]:
def jacobi(a,b):
  n = len(b)
  x_old = np.ones((n,1))
  x_new = np.ones((n,1))
  for k in range(400):
    for i in range(n):
      sum = 0
      for j in range(n):
        if i != j :
          sum += a[i][j] * x_old[j]
      x_new[i] = 1 / a[i][i] * (b[i] - sum)
    # Ο καινούριος πίνακας αντιγράφεται στον παλιό
    x_old = x_new.copy()
  return x_new

## Vectorized επίλυση

Η παραπάνω υλοποίηση της μεθόδου Jacobi δεν αξιοποιεί τις βελτιστοποιημένες συναρτήσεις/ μεθόδους της βιβλιοθήκης numpy. Μια (πολύ) πιο αποδοτική υλοποίηση μπορεί να δοθεί στην οποία πραγματοποιούμε πράξεις στο επίπεδο των πινάκων/διανυσμάτων, με χρήση τελεστών και μεθόδων της numpy, αντί για τον στοιχείο προς στοιχείο υπολογισμό της συνάρτησης `jacobi_for` που δώσαμε προηγουμένως. 

Έστω $D_A = \left(\begin{matrix}a_{11}&0&\ldots&0\\0&a_{22}&\ldots&0\\\vdots&\vdots&\ddots&\vdots\\0&0&\dots&a_{nn}\end{matrix}\right)$ ο πίνακας με τα διαγώνια στοιχεία του πίνακα $A$.

Έστω επίσης ότι  $d^{-1}_A = \left(\begin{matrix}\frac1{a_{11}}\\\frac{1}{a_{22}}\\\vdots\\\frac1{a_{nn}}\end{matrix}\right)$ είναι το διάνυσμα (πίνακας στήλη) με τα αντίστροφα των στοιχείων της διαγωνίου του πίνακα $Α$. 

Ορίζουμε την πράξη $\odot$ ως τον πίνακα με στοιχειά το γινόμενο των αντίστοιχων στοιχείων δύο πινάκων ή διανυσμάτων ίδιου σχήματος.

Τότε, μπορούμε να δούμε ότι ο αναδρομικός τύπος της μεθόδου Jacobi μπορεί να γραφεί ως

$$\textbf{x}^{(k+1)}  =  d^{-1}_A\odot\left( \textbf{b} - (A - D_A) \textbf{x}^{(k)}\right), \, \text{για } k \ge 0$$

Μια υλοποίησή της Jacobi με τεχνικές vectorization δίνεται στη συνέχεια:

In [ ]:
def jacobi_vectorized(a, b) :
  n = len(b)
  diag_vec = np.diag(a)
  diag_inv = (1 / diag_vec).reshape((n,1))
  diag_mat = np.diag(diag_vec)
  a_diag_mat = a - diag_mat
  x = np.ones(n).reshape((n,1))

  for i in range(400):
    x = diag_inv * (b - np.dot(a_diag_mat, x)) 
      
  return x

## Εφαρμογή μεθόδου

Αρχικά δημιουργούμε έναν πίνακα `a` με τυχαία στοιχεία ο οποίος να ικανοποιεί τη συνθήκη της μεθόδου Jacobi.

In [ ]:
n = 100
a = 10 * np.random.rand(n,n)
# Πρόσθεσε 1 στα στοιχεία της διαγωνίου
a = a + np.identity(n)
d = np.diag(np.diag(a))
dd = 2 * n * d
a += dd
b = 100 * n * np.random.rand(n,1)

## Αποτελέσματα 

Στη συνέχεια εμφανίζουμε τα αποτελέσματα με διαδοχική πρόσβαση στα στοιχεία, με **vectorized** τεχνικές και με χρήση έτοιμης συνάρτησης της NumPy. Επιπλέον μετράμε τον χρόνο εκτέλεσης κάθε μίας.

In [ ]:
start = time.time()
jacobi(a, b) # Υλοποίηση με πρόσβαση στα στοιχεία των πινάκων
end = time.time()
print(f"Χρόνος: {end - start} δευτερόλεπτα")

In [ ]:
start = time.time()
np.linalg.solve(a, b) # Συνάρτηση βιβλιοθήκης numpy
end = time.time()
print(f"Χρόνος: {end - start} δευτερόλεπτα")

In [ ]:
start = time.time()
jacobi_vectorized(a, b) # Vectorized υλοποίηση
end = time.time()
print(f"Χρόνος: {end - start} δευτερόλεπτα")

H **vectorized** εκδοχή, για τον ίδιο αριθμό επαναλήψεων, είναι πολλαπλάσια γρηγορότερη από την εκδοχή `jacobi`. Στη γενική περίπτωση, οι vectorized υλοποιήσεις πρέπει να προτιμώνται, εκτός εξαιρετικών περιπτώσεων.